# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: docker/cache-action@v2
      with:
        path: /tmp/.buildx-cache

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: your-registry/your-image:latest

    - name: Deploy to Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: '1.21.0'

    - name: Set up kubectl
      run: kubectl apply -f kubernetes/

    - name: Check kubectl version
      run: kubectl version
